### ISSUE TITLE
Invalid HTML iframe code

### ISSUE THREAD

**Issue by KTobi8** [nextgenthemes/advanced-responsive-video-embedder#19]
Invalid code frameborder="0".
I read, that it has to change to style="border:0;".
After change, it's valid, and work good for me.

I change function create_iframe, class-advanced-responsive-video-embedder-public.php line 795
from: 'frameborder'     => '0',
to: 'style'     => 'border:0;',

If it's ok, include it in the next update.

**Comment by nextgenthemes** [comment]
Well its not that easy because (some older versions?) of IE actually need it or they display a border. I am not sure if I should get into the complication if browser detection to just include it when the browsers is IE (not even sure what versions need it) just to satisfy a robot.

The attribute is recognized by all browsers despite it not being "valid" HTML5.
